### PR TITLE
Add support for ARM

### PR DESCRIPTION
**Pull request by dillstead**

### CODE REVIEW

**Comment by Keith-Cancel** [comment]
Hello,

Thanks for the pull request let me review and test some things.

**Comment by dillstead** [comment]
No problem, I ran a few of my own tests on each function which I didn't commit and they worked. Let me know what you find.

**Comment by Keith-Cancel** [comment]
It seems to work fine. All the non-volatile registers are saved for standard ARM calling convention.  The submitted code is plenty readable.

Also thanks for catching the error in the readme regarding `bunki_data_set`.

**Comment by dillstead** [comment]
No problem, it was a nice little project for me to break out some 32-bit ARM assembly :-)

**Pull request merged**
